### ISSUE TITLE
Does not build with libhttpserver 2.0

### ISSUE THREAD

**Issue by nwhitehorn** [gsmecher/tuberd#93]
Encountered build errors with the new release of libhttpserver:

[ 50%] Building CXX object CMakeFiles/_tuber_runtime.dir/src/server.cpp.o
In file included from /home/nwhitehorn/buildroot.71/buildroot/output/build/tuber-0.18.4/src/server.cpp:8:
/home/nwhitehorn/buildroot.71/buildroot/output/host/riscv64-buildroot-linux-gnu/sysroot/usr/include/httpserver.hpp:25:4: error: #error ("libhttpserver requires C++20 or later.")
   25 | #  error("libhttpserver requires C++20 or later.")
      |    ^~~~~

After setting the C++ standard, there are many more errors -- there seem to have been major API changes.
